name: cmplr
description: A mimic to Tumblr application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  
  get: ^4.3.8
  flutter_keyboard_visibility: ^5.1.0
  getwidget: ^2.0.4
  google_fonts: 
  fluttertoast: 
  progress_indicators:
  google_sign_in: 
  url_launcher:
  get_storage:
  firebase_core:
  firebase_auth: ^3.3.3
  driver_extensions:
  share_plus:

  file_picker:
  flutter_html:
  intl:
  metadata_fetch: 

  # Original package is old and has dependency issues
  # Using fork for now
  # flutter_link_preview:
  #   git: 'https://github.com/ItzNotABug/flutter_link_preview'
  # focused_menu: Since we have our own modified version

dev_dependencies:
  flutter_native_splash: 
  flutter_launcher_icons:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


flutter:
  uses-material-design: true
  fonts:
    - family: CustomIcons
      fonts:
        - asset: lib/utilities/custom_icons/CustomIcons.ttf

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/utilities/assets/
    - lib/utilities/assets/logo/
    - lib/utilities/assets/intro_screen/
    - lib/utilities/assets/logo/

flutter_native_splash: # flutter clean && flutter pub get && flutter pub run flutter_native_splash:create
  color: "#001935"
  image: lib/utilities/assets/logo/trans_logo.png
  android: true
  ios: true
  web: true

flutter_icons: # flutter clean && flutter pub get && flutter pub run flutter_launcher_icons:main
  android: "launcher_icon"
  ios: true
  image_path: lib/utilities/assets/logo/logo_icon.png
  adaptive_icon_background: "#000000"


